version: '3'

services:
  daas:
    build: .
    volumes:
      #- /ida:/ida
      - daas-db:/db
        #- $HOME/.idapro/ida.reg:/root/.idapro/ida.reg
    ports:
      - 8000:8000
    environment:
      DB_URI: sqlite:////db/daas.py
    networks:
      - daas

volumes:
  daas-db:

networks:
  daas:
